title: SWR Sports Data Analysis
description: "Data‐driven insights into your favorite sports, teams, and athletes"

# Must include this so GitHub Pages knows to use remote themes
plugins:
  - jekyll-remote-theme

# this is the only theme key you need
remote_theme: pages-themes/cayman@v0.2.0

# leave “theme:” blank or omit it entirely
# theme:

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
